title: "Hello Programming World"
description: "Blog about programming, sitecore and everything else."
author: "Bartłomiej Mucha"
url: https://www.bartlomiejmucha.com

google_analytics_id: UA-51153105-1

permalink: "/en/blog/:categories/:title"
remote_theme: bartlomiejmucha/blog@theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never